---
    - hosts: ec2_instances
      tasks:
        - name: Upgrade All Packages
          yum:
            name: '*'
            state: latest
        - name: Install Docker
          shell:
            cmd: sudo amazon-linux-extras install docker -y
            warn: false
        - name: Start Docker Service
          ansible.buitin.service:
            name: docker
            state: started
        - name: Add User Docker On Group
          shell:
            cmd: sudo usermod -a -G docker ec2-user
            warn: false
        - name: Install Docker-Compose
          shell:
            cmd: sudo curl -L https://github.com/docker/compose/releases/download/1.25.4/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
            warn: false
        - name: Copy file with owner and permissions
          ansible.builtin.copy:
            src: ../docker-compose/docker-compose.yml
            dest: /home/ec2-user/stack-compose/
            owner: ec2-user
            group: ec2-user
            mode: '0777'
        - name: Grant Permission Docker-Compose
          ansible.builtin.file:
          path: /usr/local/bin/docker-compose
          mode: '0777'
        - name: Start Docker-Compose Stack
          docker_compose:
            project_src: /home/ec2-user/stack-compose/
            file: docker-compose.yml